/*
 * wat_emit.h — §6 text out of a §5 module.
 *
 * §6.1: "The textual format for WebAssembly modules is a rendering of their abstract
 * syntax into S-expressions. … A text string is a well-formed description of a module
 * if and only if it is generated by the grammar." So emitting is choosing a
 * DERIVATION, and the derivations of one module differ only by which of §6.1.2's
 * rewrite rules were applied. Choosing among them by a cost is a min-cost cover over
 * the tree — burg's labeller — which is what wat_layout.burg is.
 *
 * Only valid text is ever produced. A module that does not pass §7.6 gets a
 * diagnostic and no output: a folded rendering is a claim about the data flow, and
 * on a body whose operand stack is wrong that claim would be a lie.
 */
#ifndef WAT_EMIT_H
#define WAT_EMIT_H

#include <stddef.h>

#include "bbq_arena.h"
#include "jav_types.h"
#include "wat_check.h"

/* Render `m` as §6 text. `width` is the column budget the layout cover lays out
 * against (§6.1.1 allows white space wherever the grammar has a space, so this
 * decides nothing about validity and everything about readability).
 *
 * Returns 1 on success, with *out / *out_len the rendered text (from `a`). Returns 0
 * if any body fails §7.6, leaving *out untouched — the verdict, and the instruction
 * it failed on, come from wat_check_body. */
int wat_emit_module(const jav_module_t* m, const wat_check_ctx_t* cx, int width,
                    bbq_arena* a, const char** out, size_t* out_len);

/* The engine's self-check, accumulated across every wat_emit_module call:
 * a group laid FLAT must emit exactly the bytes its width memo predicted —
 * the number the fit test trusted — and every emitted line must fit the
 * width except where a single unbreakable token overflows it (a long name
 * or datastring piece), which is counted, never hidden. test_wast prints
 * and gates these over both corpora. */
typedef struct {
    uint64_t flat_groups;      /* groups rendered flat */
    uint64_t width_mismatches; /* flat groups whose bytes != predicted width */
    uint64_t long_lines;       /* over-width lines with a break point available */
    uint64_t atom_overflows;   /* over-width lines that are one unbreakable token */
    uint64_t custom_unplaceable; /* §7.7.3 positions no sec word names (no `tag`) */
} wat_emit_stats_t;

void wat_emit_stats(wat_emit_stats_t* out);
void wat_emit_stats_reset(void);

/* Why the last wat_emit_module returned 0: the builder's error and the stage
 * ("build" / "label" / "cover" / "reduce" / "print") that refused. */
jav_err_t wat_emit_last_error(const char** stage);

#endif /* WAT_EMIT_H */
