/*
 * wat_emit.h — §6 text out of a §5 module.
 *
 * §6.1: "The textual format for WebAssembly modules is a rendering of their abstract
 * syntax into S-expressions. … A text string is a well-formed description of a module
 * if and only if it is generated by the grammar." So emitting is choosing a
 * DERIVATION, and the derivations of one module differ only by which of §6.1.2's
 * rewrite rules were applied. Choosing among them by a cost is a min-cost cover over
 * the tree — burg's labeller — which is what wat_layout.burg is.
 *
 * Only valid text is ever produced. A module that does not pass §7.6 gets a
 * diagnostic and no output: a folded rendering is a claim about the data flow, and
 * on a body whose operand stack is wrong that claim would be a lie.
 */
#ifndef WAT_EMIT_H
#define WAT_EMIT_H

#include <stddef.h>

#include "bbq_arena.h"
#include "jav_types.h"
#include "wat_check.h"

/* Render `m` as §6 text. `width` is the column budget the layout cover lays out
 * against (§6.1.1 allows white space wherever the grammar has a space, so this
 * decides nothing about validity and everything about readability).
 *
 * Returns 1 on success, with *out / *out_len the rendered text (from `a`). Returns 0
 * if any body fails §7.6, leaving *out untouched — the verdict, and the instruction
 * it failed on, come from wat_check_body. */
int wat_emit_module(const jav_module_t* m, const wat_check_ctx_t* cx, int width,
                    bbq_arena* a, const char** out, size_t* out_len);

#endif /* WAT_EMIT_H */
