package javelina.simd;

// AUTO-GENERATED by tools/gen_simd_intrinsics.c from the spec's
// instructions.toml — do not edit. Every method is a compiler
// intrinsic: sema stamps it, the ddcg lowers it to its wasm opcode
// inline, and it is NEVER a host import. `native` is the stamped-
// intrinsic convention (the Math.sqrt pattern).
// F32x4: the f32x4-shaped lane view of a V128.
public final class F32x4 {
    private F32x4() {}

    public static native V128 splat(float a);
    public static native float extract_lane(V128 a, int lane);
    public static native V128 replace_lane(V128 a, float b, int lane);
    public static native V128 eq(V128 a, V128 b);
    public static native V128 ne(V128 a, V128 b);
    public static native V128 lt(V128 a, V128 b);
    public static native V128 gt(V128 a, V128 b);
    public static native V128 le(V128 a, V128 b);
    public static native V128 ge(V128 a, V128 b);
    public static native V128 demote_f64x2_zero(V128 a);
    public static native V128 ceil(V128 a);
    public static native V128 floor(V128 a);
    public static native V128 trunc(V128 a);
    public static native V128 nearest(V128 a);
    public static native V128 abs(V128 a);
    public static native V128 neg(V128 a);
    public static native V128 sqrt(V128 a);
    public static native V128 add(V128 a, V128 b);
    public static native V128 sub(V128 a, V128 b);
    public static native V128 mul(V128 a, V128 b);
    public static native V128 div(V128 a, V128 b);
    public static native V128 min(V128 a, V128 b);
    public static native V128 max(V128 a, V128 b);
    public static native V128 pmin(V128 a, V128 b);
    public static native V128 pmax(V128 a, V128 b);
    public static native V128 convert_i32x4_s(V128 a);
    public static native V128 convert_i32x4_u(V128 a);
    public static native V128 relaxed_madd(V128 a, V128 b, V128 c);
    public static native V128 relaxed_nmadd(V128 a, V128 b, V128 c);
    public static native V128 relaxed_min(V128 a, V128 b);
    public static native V128 relaxed_max(V128 a, V128 b);
}
