package javelina.simd;

// AUTO-GENERATED by tools/gen_simd_intrinsics.c from the spec's
// instructions.toml — do not edit. Every method is a compiler
// intrinsic: sema stamps it, the ddcg lowers it to its wasm opcode
// inline, and it is NEVER a host import. `native` is the stamped-
// intrinsic convention (the Math.sqrt pattern).
// I16x8: the i16x8-shaped lane view of a V128.
public final class I16x8 {
    private I16x8() {}

    public static native V128 splat(int a);
    public static native int extract_lane_s(V128 a, int lane);
    public static native int extract_lane_u(V128 a, int lane);
    public static native V128 replace_lane(V128 a, int b, int lane);
    public static native V128 eq(V128 a, V128 b);
    public static native V128 ne(V128 a, V128 b);
    public static native V128 lt_s(V128 a, V128 b);
    public static native V128 lt_u(V128 a, V128 b);
    public static native V128 gt_s(V128 a, V128 b);
    public static native V128 gt_u(V128 a, V128 b);
    public static native V128 le_s(V128 a, V128 b);
    public static native V128 le_u(V128 a, V128 b);
    public static native V128 ge_s(V128 a, V128 b);
    public static native V128 ge_u(V128 a, V128 b);
    public static native V128 extadd_pairwise_i8x16_s(V128 a);
    public static native V128 extadd_pairwise_i8x16_u(V128 a);
    public static native V128 abs(V128 a);
    public static native V128 neg(V128 a);
    public static native V128 q15mulr_sat_s(V128 a, V128 b);
    public static native int all_true(V128 a);
    public static native int bitmask(V128 a);
    public static native V128 narrow_i32x4_s(V128 a, V128 b);
    public static native V128 narrow_i32x4_u(V128 a, V128 b);
    public static native V128 extend_low_i8x16_s(V128 a);
    public static native V128 extend_high_i8x16_s(V128 a);
    public static native V128 extend_low_i8x16_u(V128 a);
    public static native V128 extend_high_i8x16_u(V128 a);
    public static native V128 shl(V128 a, int b);
    public static native V128 shr_s(V128 a, int b);
    public static native V128 shr_u(V128 a, int b);
    public static native V128 add(V128 a, V128 b);
    public static native V128 add_sat_s(V128 a, V128 b);
    public static native V128 add_sat_u(V128 a, V128 b);
    public static native V128 sub(V128 a, V128 b);
    public static native V128 sub_sat_s(V128 a, V128 b);
    public static native V128 sub_sat_u(V128 a, V128 b);
    public static native V128 mul(V128 a, V128 b);
    public static native V128 min_s(V128 a, V128 b);
    public static native V128 min_u(V128 a, V128 b);
    public static native V128 max_s(V128 a, V128 b);
    public static native V128 max_u(V128 a, V128 b);
    public static native V128 avgr_u(V128 a, V128 b);
    public static native V128 extmul_low_i8x16_s(V128 a, V128 b);
    public static native V128 extmul_high_i8x16_s(V128 a, V128 b);
    public static native V128 extmul_low_i8x16_u(V128 a, V128 b);
    public static native V128 extmul_high_i8x16_u(V128 a, V128 b);
    public static native V128 relaxed_laneselect(V128 a, V128 b, V128 c);
    public static native V128 relaxed_q15mulr_s(V128 a, V128 b);
    public static native V128 relaxed_dot_i8x16_i7x16_s(V128 a, V128 b);
}
