package javelina.simd;

// AUTO-GENERATED by tools/gen_simd_intrinsics.c from the spec's
// instructions.toml — do not edit. Every method is a compiler
// intrinsic: sema stamps it, the ddcg lowers it to its wasm opcode
// inline, and it is NEVER a host import. `native` is the stamped-
// intrinsic convention (the Math.sqrt pattern).
// I32x4: the i32x4-shaped lane view of a V128.
public final class I32x4 {
    private I32x4() {}

    public static native V128 splat(int a);
    public static native int extract_lane(V128 a, int lane);
    public static native V128 replace_lane(V128 a, int b, int lane);
    public static native V128 eq(V128 a, V128 b);
    public static native V128 ne(V128 a, V128 b);
    public static native V128 lt_s(V128 a, V128 b);
    public static native V128 lt_u(V128 a, V128 b);
    public static native V128 gt_s(V128 a, V128 b);
    public static native V128 gt_u(V128 a, V128 b);
    public static native V128 le_s(V128 a, V128 b);
    public static native V128 le_u(V128 a, V128 b);
    public static native V128 ge_s(V128 a, V128 b);
    public static native V128 ge_u(V128 a, V128 b);
    public static native V128 extadd_pairwise_i16x8_s(V128 a);
    public static native V128 extadd_pairwise_i16x8_u(V128 a);
    public static native V128 abs(V128 a);
    public static native V128 neg(V128 a);
    public static native int all_true(V128 a);
    public static native int bitmask(V128 a);
    public static native V128 extend_low_i16x8_s(V128 a);
    public static native V128 extend_high_i16x8_s(V128 a);
    public static native V128 extend_low_i16x8_u(V128 a);
    public static native V128 extend_high_i16x8_u(V128 a);
    public static native V128 shl(V128 a, int b);
    public static native V128 shr_s(V128 a, int b);
    public static native V128 shr_u(V128 a, int b);
    public static native V128 add(V128 a, V128 b);
    public static native V128 sub(V128 a, V128 b);
    public static native V128 mul(V128 a, V128 b);
    public static native V128 min_s(V128 a, V128 b);
    public static native V128 min_u(V128 a, V128 b);
    public static native V128 max_s(V128 a, V128 b);
    public static native V128 max_u(V128 a, V128 b);
    public static native V128 dot_i16x8_s(V128 a, V128 b);
    public static native V128 extmul_low_i16x8_s(V128 a, V128 b);
    public static native V128 extmul_high_i16x8_s(V128 a, V128 b);
    public static native V128 extmul_low_i16x8_u(V128 a, V128 b);
    public static native V128 extmul_high_i16x8_u(V128 a, V128 b);
    public static native V128 trunc_sat_f32x4_s(V128 a);
    public static native V128 trunc_sat_f32x4_u(V128 a);
    public static native V128 trunc_sat_f64x2_s_zero(V128 a);
    public static native V128 trunc_sat_f64x2_u_zero(V128 a);
    public static native V128 relaxed_trunc_f32x4_s(V128 a);
    public static native V128 relaxed_trunc_f32x4_u(V128 a);
    public static native V128 relaxed_trunc_f64x2_s_zero(V128 a);
    public static native V128 relaxed_trunc_f64x2_u_zero(V128 a);
    public static native V128 relaxed_laneselect(V128 a, V128 b, V128 c);
    public static native V128 relaxed_dot_i8x16_i7x16_add_s(V128 a, V128 b, V128 c);
}
