package javelina.simd;

// AUTO-GENERATED by tools/gen_simd_intrinsics.c from the spec's
// instructions.toml — do not edit. Every method is a compiler
// intrinsic: sema stamps it, the ddcg lowers it to its wasm opcode
// inline, and it is NEVER a host import. `native` is the stamped-
// intrinsic convention (the Math.sqrt pattern).
// I64x2: the i64x2-shaped lane view of a V128.
public final class I64x2 {
    private I64x2() {}

    public static native V128 splat(long a);
    public static native long extract_lane(V128 a, int lane);
    public static native V128 replace_lane(V128 a, long b, int lane);
    public static native V128 abs(V128 a);
    public static native V128 neg(V128 a);
    public static native int all_true(V128 a);
    public static native int bitmask(V128 a);
    public static native V128 extend_low_i32x4_s(V128 a);
    public static native V128 extend_high_i32x4_s(V128 a);
    public static native V128 extend_low_i32x4_u(V128 a);
    public static native V128 extend_high_i32x4_u(V128 a);
    public static native V128 shl(V128 a, int b);
    public static native V128 shr_s(V128 a, int b);
    public static native V128 shr_u(V128 a, int b);
    public static native V128 add(V128 a, V128 b);
    public static native V128 sub(V128 a, V128 b);
    public static native V128 mul(V128 a, V128 b);
    public static native V128 eq(V128 a, V128 b);
    public static native V128 ne(V128 a, V128 b);
    public static native V128 lt_s(V128 a, V128 b);
    public static native V128 gt_s(V128 a, V128 b);
    public static native V128 le_s(V128 a, V128 b);
    public static native V128 ge_s(V128 a, V128 b);
    public static native V128 extmul_low_i32x4_s(V128 a, V128 b);
    public static native V128 extmul_high_i32x4_s(V128 a, V128 b);
    public static native V128 extmul_low_i32x4_u(V128 a, V128 b);
    public static native V128 extmul_high_i32x4_u(V128 a, V128 b);
    public static native V128 relaxed_laneselect(V128 a, V128 b, V128 c);
}
