package javelina.simd;

// AUTO-GENERATED by tools/gen_simd_intrinsics.c from the spec's
// instructions.toml — do not edit. Every method is a compiler
// intrinsic: sema stamps it, the ddcg lowers it to its wasm opcode
// inline, and it is NEVER a host import. `native` is the stamped-
// intrinsic convention (the Math.sqrt pattern).
// Mem: the module's linear memory. Methods keep the full wasm
// mnemonic ('.'->'_'); addresses are byte offsets (int); memory_grow
// takes/returns 64 KiB pages (old size, or -1 on failure — the wasm
// contract, surfaced as the return value). The low pages carry the
// runtime's transient host-I/O staging traffic DURING library calls;
// user data and I/O never run concurrently (single-threaded), so the
// memory is one flat user-managed space between calls.
public final class Mem {
    private Mem() {}

    public static native int i32_load(int a);
    public static native long i64_load(int a);
    public static native float f32_load(int a);
    public static native double f64_load(int a);
    public static native int i32_load8_s(int a);
    public static native int i32_load8_u(int a);
    public static native int i32_load16_s(int a);
    public static native int i32_load16_u(int a);
    public static native long i64_load8_s(int a);
    public static native long i64_load8_u(int a);
    public static native long i64_load16_s(int a);
    public static native long i64_load16_u(int a);
    public static native long i64_load32_s(int a);
    public static native long i64_load32_u(int a);
    public static native void i32_store(int a, int b);
    public static native void i64_store(int a, long b);
    public static native void f32_store(int a, float b);
    public static native void f64_store(int a, double b);
    public static native void i32_store8(int a, int b);
    public static native void i32_store16(int a, int b);
    public static native void i64_store8(int a, long b);
    public static native void i64_store16(int a, long b);
    public static native void i64_store32(int a, long b);
    public static native int memory_size();
    public static native int memory_grow(int a);
    public static native void memory_copy(int a, int b, int c);
    public static native void memory_fill(int a, int b, int c);
    public static native V128 v128_load(int a);
    public static native V128 v128_load8x8_s(int a);
    public static native V128 v128_load8x8_u(int a);
    public static native V128 v128_load16x4_s(int a);
    public static native V128 v128_load16x4_u(int a);
    public static native V128 v128_load32x2_s(int a);
    public static native V128 v128_load32x2_u(int a);
    public static native V128 v128_load8_splat(int a);
    public static native V128 v128_load16_splat(int a);
    public static native V128 v128_load32_splat(int a);
    public static native V128 v128_load64_splat(int a);
    public static native void v128_store(int a, V128 b);
    public static native V128 v128_load8_lane(int a, V128 b, int lane);
    public static native V128 v128_load16_lane(int a, V128 b, int lane);
    public static native V128 v128_load32_lane(int a, V128 b, int lane);
    public static native V128 v128_load64_lane(int a, V128 b, int lane);
    public static native void v128_store8_lane(int a, V128 b, int lane);
    public static native void v128_store16_lane(int a, V128 b, int lane);
    public static native void v128_store32_lane(int a, V128 b, int lane);
    public static native void v128_store64_lane(int a, V128 b, int lane);
    public static native V128 v128_load32_zero(int a);
    public static native V128 v128_load64_zero(int a);

    // Bounce helpers: GC arrays <-> linear memory, plain Java over the ops
    // (E8.3). Bounds come from the ops' own guards + the array checks.
    public static void copyIn(byte[] src, int off, int len, int addr) {
        for (int i = 0; i < len; i++) i32_store8(addr + i, src[off + i]);
    }
    public static void copyOut(int addr, byte[] dst, int off, int len) {
        for (int i = 0; i < len; i++) dst[off + i] = (byte) i32_load8_u(addr + i);
    }
    public static void copyIn(javelina.simd.V128[] src, int off, int len, int addr) {
        for (int i = 0; i < len; i++) v128_store(addr + i * 16, src[off + i]);
    }
    public static void copyOut(int addr, javelina.simd.V128[] dst, int off, int len) {
        for (int i = 0; i < len; i++) dst[off + i] = v128_load(addr + i * 16);
    }
}
