package javelina.simd;

// AUTO-GENERATED by tools/gen_simd_intrinsics.c from the spec's
// instructions.toml — do not edit. Every method is a compiler
// intrinsic: sema stamps it, the ddcg lowers it to its wasm opcode
// inline, and it is NEVER a host import. `native` is the stamped-
// intrinsic convention (the Math.sqrt pattern).
// V128 is also THE v128 VALUE type: sema maps this class to the
// v128 value width at every use site — never a reference, never
// null, no ==, no Object conversion.
public final class V128 {
    private V128() {}

    public static native V128 const_(long lo, long hi);
    public static native V128 not(V128 a);
    public static native V128 and(V128 a, V128 b);
    public static native V128 andnot(V128 a, V128 b);
    public static native V128 or(V128 a, V128 b);
    public static native V128 xor(V128 a, V128 b);
    public static native V128 bitselect(V128 a, V128 b, V128 c);
    public static native int any_true(V128 a);
}
