/* gen_eqsat_ops.c — the tier-3 e-node admission fence, from the spec table.
 *
 * One authority (the working analog's law: "One definition of purity, not
 * two"): which opcodes may intern as PURE e-nodes is generated from
 * spec/instructions.toml, never hand-listed in jav_eqsat.c. Emits
 * src/gen/jav_eqsat_ops.h.
 *
 * The predicate, from the plan's D2 ("traps == [] plus the shape/family
 * facts already in the toml"):
 *
 *   admitted  <=>  the opcode is a plain byte (the prefixed families are
 *                  outside the v1 vocabulary)
 *              AND `traps` is empty (a trapping op is not a value equality —
 *                  WASM §4.3's div/rem/trunc partiality)
 *              AND the name is in the i32./i64. families (integer arithmetic
 *                  is defined modulo 2^N, §4.3.2 — total, deterministic;
 *                  floats stay OPAQUE by D8: NaN payload nondeterminism
 *                  makes syntactic equality weaker than value equality, and
 *                  locals/globals/memory/refs/control are state, not value).
 *
 * The axiom file may mention fewer ops than this fence admits; it may never
 * mention more — jav_eqsat.c interns only what this table admits, so a rule
 * over an unadmitted op simply never matches.
 */
#include "toml/toml_doc.h"
#include "bbq_arena.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static char* slurp(const char* path, int* len) {
    FILE* f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "gen_eqsat_ops: cannot open %s\n", path); exit(1); }
    fseek(f, 0, SEEK_END); long n = ftell(f); fseek(f, 0, SEEK_SET);
    char* b = malloc((size_t)n + 1);
    if (!b || fread(b, 1, (size_t)n, f) != (size_t)n) {
        fprintf(stderr, "gen_eqsat_ops: cannot read %s\n", path); exit(1);
    }
    b[n] = 0; fclose(f); *len = (int)n; return b;
}

int main(int argc, char** argv) {
    if (argc != 3) {
        fprintf(stderr, "usage: gen_eqsat_ops <instructions.toml> <out.h>\n");
        return 2;
    }
    bbq_arena ar; bbq_arena_init(&ar, 1 << 20);
    int len; char* src = slurp(argv[1], &len);
    toml_doc_t* doc = toml_parse(src, len, &ar);
    if (toml_doc_has_errors(doc)) {
        fprintf(stderr, "gen_eqsat_ops: %s: %s\n", argv[1],
                toml_doc_error_at(doc, 0)->message);
        return 1;
    }
    const toml_val_t* instrs = toml_tbl_get(toml_doc_root(doc), "instr");
    int n = toml_val_array_count(instrs);
    if (n == 0) { fprintf(stderr, "gen_eqsat_ops: no [[instr]] entries\n"); return 1; }

    uint8_t pure[256] = {0};
    char why[256][40] = {{0}};
    int npure = 0;
    for (int i = 0; i < n; i++) {
        const toml_tbl_t* t = toml_val_as_table(toml_val_array_at(instrs, i));
        if (!t) continue;
        const toml_val_t* opv = toml_tbl_get(t, "opcode");
        int64_t op;
        if (!toml_val_as_int(opv, &op)) continue;      /* [prefix, sub]: out of v1 */
        if (op < 0 || op > 255) {
            fprintf(stderr, "gen_eqsat_ops: opcode %lld out of byte range\n",
                    (long long)op);
            return 1;
        }
        const char* name;
        if (!toml_val_as_string(toml_tbl_get(t, "name"), &name)) continue;
        const toml_val_t* traps = toml_tbl_get(t, "traps");
        if (traps && toml_val_array_count(traps) > 0) continue;
        if (strncmp(name, "i32.", 4) != 0 && strncmp(name, "i64.", 4) != 0) continue;
        if (pure[op]) {
            fprintf(stderr, "gen_eqsat_ops: opcode 0x%02x listed twice (%s, %s)\n",
                    (unsigned)op, why[op], name);
            return 1;
        }
        pure[op] = 1;
        snprintf(why[op], sizeof why[op], "%s", name);
        npure++;
    }
    if (npure == 0) {
        fprintf(stderr, "gen_eqsat_ops: the fence admitted nothing — the predicate "
                        "or the table is broken\n");
        return 1;
    }

    FILE* o = fopen(argv[2], "w");
    if (!o) { fprintf(stderr, "gen_eqsat_ops: cannot write %s\n", argv[2]); return 1; }
    fprintf(o,
        "/* AUTO-GENERATED by tools/gen_eqsat_ops.c from spec/instructions.toml —\n"
        " * do not edit. The tier-3 e-node admission fence: 1 = this unprefixed\n"
        " * opcode is a total, deterministic integer op (traps == [], i32./i64.\n"
        " * family) and may intern as a pure e-node. Everything else is OPAQUE —\n"
        " * interned by identity, its pure subtrees still graphed. %d admitted. */\n"
        "#ifndef JAV_EQSAT_OPS_H\n#define JAV_EQSAT_OPS_H\n\n"
        "#include <stdint.h>\n\n"
        "static const uint8_t jav_eqsat_pure[256] = {\n", npure);
    for (int op = 0; op < 256; op++)
        if (pure[op]) fprintf(o, "    [0x%02x] = 1,  /* %s */\n", op, why[op]);
    fprintf(o,
        "};\n\n"
        "/* Synthetic e-node operators, disjoint from every opcode byte.\n"
        " * A local.get interns as (JAV_EQ_OP_LOCAL, data = slot | version<<32)\n"
        " * — the plan's D3a versioned leaf — and an unadmitted subtree as\n"
        " * (JAV_EQ_OP_OPAQUE, data = the jav_tnode_t address): its own\n"
        " * congruence class, no inputs, the tree keeps its place. */\n"
        "#define JAV_EQ_OP_LOCAL  0x100\n"
        "#define JAV_EQ_OP_OPAQUE 0x101\n"
        "\n#endif /* JAV_EQSAT_OPS_H */\n");
    fclose(o);
    fprintf(stderr, "gen_eqsat_ops: %d pure opcode(s)\n", npure);
    return 0;
}
