// Generated by pegc — do not edit
package javelina.peg;

import javelina.peg.RegexBuilder;
   import javelina.peg.RegexParse;
   import javelina.peg.RAnchorEnd;
   import javelina.peg.RAnchorStart;
   import javelina.peg.RAny;
   import javelina.peg.RAtomic;
   import javelina.peg.RGroup;
   import javelina.peg.RLookahead;
   import javelina.peg.RNegLookahead;
   import javelina.peg.Rexp;

public class RegexParser {
    private PegCursor p;

    public RegexParser(char[] input) {
        p = new PegCursor(input);
        setupSkip();
    }

    public PegCursor cursor() {
        return p;
    }

    public boolean parse() {
        p.skip();
        return parse_regex();
    }

    private static boolean is_digit(char c) {
        return (c >= 48 && c <= 57);
    }

    private static boolean is_digit19(char c) {
        return (c >= 49 && c <= 57);
    }

    private static boolean is_meta(char c) {
        return ((((((((((((((c == 124) || (c == 42)) || (c == 43)) || (c == 63)) || (c == 40)) || (c == 41)) || (c == 91)) || (c == 93)) || (c == 123)) || (c == 125)) || (c == 46)) || (c == 92)) || (c == 94)) || (c == 36));
    }

    private static boolean is_plain(char c) {
        return (true && !(is_meta(c)));
    }

    private static boolean is_classch(char c) {
        return ((true && !((c == 93))) && !((c == 92)));
    }

    private void setupSkip() {
    }

    private boolean parse_regex() {
        RegexParse st = (RegexParse) p.userData;
       Rexp[] out = new Rexp[1];
        p.skip();
        if (!parse_alt(out)) return false;
        st.result = out[0];
        return true;
    }

    private boolean parse_alt(Rexp[] out) {
        Rexp[] r = new Rexp[1];
        p.skip();
        if (!parse_concat(out)) return false;
        for (;;) {
            int _m0 = p.save();
            boolean _ok0 = false;
            do {
                p.skip();
                if (!p.match("|")) break;
                p.skip();
                if (!parse_concat(r)) break;
                out[0] = RegexBuilder.alt(out[0], r[0]);
                _ok0 = true;
            } while (false);
            if (!_ok0) { p.restore(_m0); break; }
        }
        return true;
    }

    private boolean parse_concat(Rexp[] out) {
        Rexp[] r = new Rexp[1]; out[0] = null;
        for (;;) {
            int _m0 = p.save();
            boolean _ok0 = false;
            do {
                p.skip();
                if (!parse_quantified(r)) break;
                out[0] = RegexBuilder.seq(out[0], r[0]);
                _ok0 = true;
            } while (false);
            if (!_ok0) { p.restore(_m0); break; }
        }
        if (out[0] == null) out[0] = RegexBuilder.empty();
        return true;
    }

    private boolean parse_quantified(Rexp[] out) {
        char[] kind = new char[1]; char[] mod = new char[1];
       int[] bounds = new int[2];
        p.skip();
        if (!parse_atom(out)) return false;
        {
            int _m0 = p.save();
            boolean _ok0 = false;
            do {
                _choice_done1: {
                    int _m1 = p.save();
                    {
                        boolean _ok2 = false;
                        do {
                            p.skip();
                            if (!parse_quantifier(kind, mod)) break;
                            out[0] = RegexBuilder.quantify(out[0], kind[0], mod[0]);
                            _ok2 = true;
                        } while (false);
                        if (!_ok2) {
                            p.restore(_m1);
                        } else break _choice_done1;
                    }
                    p.skip();
                    if (!parse_bounded(bounds)) break;
                    out[0] = RegexBuilder.bounded(out[0], bounds[0], bounds[1]);
                }
                _ok0 = true;
            } while (false);
            if (!_ok0) p.restore(_m0);
        }
        return true;
    }

    private boolean parse_quantifier(char[] kind, char[] mod) {
        mod[0] = ' ';
        p.skip();
        if (p.peekAt("*")) {
            p.skip();
            if (!p.match("*")) return false;
            kind[0] = '*';
        } else         if (p.peekAt("+")) {
            p.skip();
            if (!p.match("+")) return false;
            kind[0] = '+';
        } else {
            p.skip();
            if (!p.match("?")) return false;
            kind[0] = '?';
        }
        {
            int _m0 = p.save();
            boolean _ok0 = false;
            do {
                p.skip();
                if (p.peekAt("+")) {
                    p.skip();
                    if (!p.match("+")) break;
                    mod[0] = '+';
                } else {
                    p.skip();
                    if (!p.match("?")) break;
                    mod[0] = '?';
                }
                _ok0 = true;
            } while (false);
            if (!_ok0) p.restore(_m0);
        }
        return true;
    }

    private boolean parse_bounded(int[] bounds) {
        int[] a = new int[1]; int[] b = new int[1];
       boolean[] comma = new boolean[1]; b[0] = -2;
        p.skip();
        if (!p.match("{")) return false;
        p.skip();
        if (!parse_number(a)) return false;
        {
            int _m0 = p.save();
            boolean _ok0 = false;
            do {
                p.skip();
                if (!p.match(",")) break;
                comma[0] = true;
                {
                    int _m1 = p.save();
                    boolean _ok1 = false;
                    do {
                        p.skip();
                        if (!parse_number(b)) break;
                        _ok1 = true;
                    } while (false);
                    if (!_ok1) p.restore(_m1);
                }
                _ok0 = true;
            } while (false);
            if (!_ok0) p.restore(_m0);
        }
        p.skip();
        if (!p.match("}")) return false;
        bounds[0] = a[0];
         bounds[1] = comma[0] ? ((b[0] == -2) ? -1 : b[0]) : a[0];
        return true;
    }

    private boolean parse_number(int[] out) {
        int v = 0;
        if (p.atEnd() || !is_digit(p.peekChar())) return false;
        p.advance();
        v = p.charAt(p.save() - 1) - '0';
        for (;;) {
            int _m0 = p.save();
            boolean _ok0 = false;
            do {
                if (p.atEnd() || !is_digit(p.peekChar())) break;
                p.advance();
                v = v * 10 + (p.charAt(p.save() - 1) - '0');
                _ok0 = true;
            } while (false);
            if (!_ok0) { p.restore(_m0); break; }
        }
        out[0] = v;
        return true;
    }

    private boolean parse_atom(Rexp[] out) {
        _choice_done0: {
            int _m0 = p.save();
            {
                boolean _ok1 = false;
                do {
                    p.skip();
                    if (!parse_group(out)) break;
                    _ok1 = true;
                } while (false);
                if (!_ok1) {
                    p.restore(_m0);
                } else break _choice_done0;
            }
            {
                boolean _ok2 = false;
                do {
                    p.skip();
                    if (!parse_class(out)) break;
                    _ok2 = true;
                } while (false);
                if (!_ok2) {
                    p.restore(_m0);
                } else break _choice_done0;
            }
            {
                boolean _ok3 = false;
                do {
                    p.skip();
                    if (!p.match(".")) break;
                    out[0] = new RAny();
                    _ok3 = true;
                } while (false);
                if (!_ok3) {
                    p.restore(_m0);
                } else break _choice_done0;
            }
            {
                boolean _ok4 = false;
                do {
                    p.skip();
                    if (!p.match("^")) break;
                    out[0] = new RAnchorStart();
                    _ok4 = true;
                } while (false);
                if (!_ok4) {
                    p.restore(_m0);
                } else break _choice_done0;
            }
            {
                boolean _ok5 = false;
                do {
                    p.skip();
                    if (!p.match("$")) break;
                    out[0] = new RAnchorEnd();
                    _ok5 = true;
                } while (false);
                if (!_ok5) {
                    p.restore(_m0);
                } else break _choice_done0;
            }
            {
                boolean _ok6 = false;
                do {
                    p.skip();
                    if (!parse_escape(out)) break;
                    _ok6 = true;
                } while (false);
                if (!_ok6) {
                    p.restore(_m0);
                } else break _choice_done0;
            }
            if (p.atEnd() || !is_plain(p.peekChar())) return false;
            p.advance();
            out[0] = RegexBuilder.literal(p.charAt(p.save() - 1));
        }
        return true;
    }

    private boolean parse_group(Rexp[] out) {
        int slot = -1;
        p.skip();
        if (!p.match("(")) return false;
        _choice_done0: {
            int _m0 = p.save();
            {
                boolean _ok1 = false;
                do {
                    p.skip();
                    if (!p.match("?:")) break;
                    p.skip();
                    if (!parse_alt(out)) break;
                    p.skip();
                    if (!p.match(")")) break;
                    _ok1 = true;
                } while (false);
                if (!_ok1) {
                    p.restore(_m0);
                } else break _choice_done0;
            }
            {
                boolean _ok2 = false;
                do {
                    p.skip();
                    if (!p.match("?=")) break;
                    p.skip();
                    if (!parse_alt(out)) break;
                    p.skip();
                    if (!p.match(")")) break;
                    out[0] = new RLookahead(out[0]);
                    _ok2 = true;
                } while (false);
                if (!_ok2) {
                    p.restore(_m0);
                } else break _choice_done0;
            }
            {
                boolean _ok3 = false;
                do {
                    p.skip();
                    if (!p.match("?!")) break;
                    p.skip();
                    if (!parse_alt(out)) break;
                    p.skip();
                    if (!p.match(")")) break;
                    out[0] = new RNegLookahead(out[0]);
                    _ok3 = true;
                } while (false);
                if (!_ok3) {
                    p.restore(_m0);
                } else break _choice_done0;
            }
            {
                boolean _ok4 = false;
                do {
                    p.skip();
                    if (!p.match("?>")) break;
                    p.skip();
                    if (!parse_alt(out)) break;
                    p.skip();
                    if (!p.match(")")) break;
                    out[0] = new RAtomic(out[0]);
                    _ok4 = true;
                } while (false);
                if (!_ok4) {
                    p.restore(_m0);
                } else break _choice_done0;
            }
            slot = ((RegexParse) p.userData).slots++;
            p.skip();
            if (!parse_alt(out)) return false;
            p.skip();
            if (!p.match(")")) return false;
            out[0] = new RGroup(slot, out[0]);
        }
        return true;
    }

    private boolean parse_escape(Rexp[] out) {
        p.skip();
        if (!p.match("\\")) return false;
        _choice_done0: {
            int _m0 = p.save();
            {
                boolean _ok1 = false;
                do {
                    if (p.atEnd() || !is_digit19(p.peekChar())) break;
                    p.advance();
                    throw new javelina.peg.PegException(
                    "backreferences are not supported: no parsing expression "
                    + "grammar can express one");
                    _ok1 = true;
                } while (false);
                if (!_ok1) {
                    p.restore(_m0);
                } else break _choice_done0;
            }
            {
                boolean _ok2 = false;
                do {
                    _choice_done3: {
                        int _m3 = p.save();
                        {
                            boolean _ok4 = false;
                            do {
                                p.skip();
                                if (!p.match("d")) break;
                                _ok4 = true;
                            } while (false);
                            if (!_ok4) {
                                p.restore(_m3);
                            } else break _choice_done3;
                        }
                        {
                            boolean _ok5 = false;
                            do {
                                p.skip();
                                if (!p.match("D")) break;
                                _ok5 = true;
                            } while (false);
                            if (!_ok5) {
                                p.restore(_m3);
                            } else break _choice_done3;
                        }
                        {
                            boolean _ok6 = false;
                            do {
                                p.skip();
                                if (!p.match("w")) break;
                                _ok6 = true;
                            } while (false);
                            if (!_ok6) {
                                p.restore(_m3);
                            } else break _choice_done3;
                        }
                        {
                            boolean _ok7 = false;
                            do {
                                p.skip();
                                if (!p.match("W")) break;
                                _ok7 = true;
                            } while (false);
                            if (!_ok7) {
                                p.restore(_m3);
                            } else break _choice_done3;
                        }
                        {
                            boolean _ok8 = false;
                            do {
                                p.skip();
                                if (!p.match("s")) break;
                                _ok8 = true;
                            } while (false);
                            if (!_ok8) {
                                p.restore(_m3);
                            } else break _choice_done3;
                        }
                        p.skip();
                        if (!p.match("S")) break;
                    }
                    out[0] = RegexBuilder.escapeClass(p.charAt(p.save() - 1));
                    _ok2 = true;
                } while (false);
                if (!_ok2) {
                    p.restore(_m0);
                } else break _choice_done0;
            }
            if (p.atEnd()) return false;
            p.advance();
            out[0] = RegexBuilder.escapeChar(p.charAt(p.save() - 1));
        }
        return true;
    }

    private boolean parse_class(Rexp[] out) {
        RegexBuilder b = new RegexBuilder();
        p.skip();
        if (!p.match("[")) return false;
        {
            int _m0 = p.save();
            boolean _ok0 = false;
            do {
                p.skip();
                if (!p.match("^")) break;
                b.negate();
                _ok0 = true;
            } while (false);
            if (!_ok0) p.restore(_m0);
        }
        p.skip();
        if (!parse_class_item(b)) return false;
        for (;;) {
            int _m1 = p.save();
            boolean _ok1 = false;
            do {
                p.skip();
                if (!parse_class_item(b)) break;
                _ok1 = true;
            } while (false);
            if (!_ok1) { p.restore(_m1); break; }
        }
        p.skip();
        if (!p.match("]")) return false;
        out[0] = b.build();
        return true;
    }

    private boolean parse_class_item(RegexBuilder b) {
        char lo = 0;
        _choice_done0: {
            int _m0 = p.save();
            {
                boolean _ok1 = false;
                do {
                    p.skip();
                    if (!p.match("\\")) break;
                    _choice_done2: {
                        int _m2 = p.save();
                        {
                            boolean _ok3 = false;
                            do {
                                _choice_done4: {
                                    int _m4 = p.save();
                                    {
                                        boolean _ok5 = false;
                                        do {
                                            p.skip();
                                            if (!p.match("d")) break;
                                            _ok5 = true;
                                        } while (false);
                                        if (!_ok5) {
                                            p.restore(_m4);
                                        } else break _choice_done4;
                                    }
                                    {
                                        boolean _ok6 = false;
                                        do {
                                            p.skip();
                                            if (!p.match("w")) break;
                                            _ok6 = true;
                                        } while (false);
                                        if (!_ok6) {
                                            p.restore(_m4);
                                        } else break _choice_done4;
                                    }
                                    p.skip();
                                    if (!p.match("s")) break;
                                }
                                b.addEscapeClass(p.charAt(p.save() - 1));
                                _ok3 = true;
                            } while (false);
                            if (!_ok3) {
                                p.restore(_m2);
                            } else break _choice_done2;
                        }
                        if (p.atEnd()) break;
                        p.advance();
                        b.addChar(p.charAt(p.save() - 1));
                    }
                    _ok1 = true;
                } while (false);
                if (!_ok1) {
                    p.restore(_m0);
                } else break _choice_done0;
            }
            if (p.atEnd() || !is_classch(p.peekChar())) return false;
            p.advance();
            lo = p.charAt(p.save() - 1);
            {
                int _m7 = p.save();
                boolean _ok7 = false;
                do {
                    p.skip();
                    if (!p.match("-")) break;
                    if (p.atEnd() || !is_classch(p.peekChar())) break;
                    p.advance();
                    b.addRange(lo, p.charAt(p.save() - 1)); lo = 0;
                    _ok7 = true;
                } while (false);
                if (!_ok7) p.restore(_m7);
            }
            if (lo != 0) b.addChar(lo);
        }
        return true;
    }

}
