// test_wat_layout.c — the layout grammar's generated artifacts, checked
// against each other and against spec/wat.peg's production inventory.
//
// Three gates:
//
//   EveryProductionHasARule — §6.1's "well-formed iff generated by the
//   grammar" read as an inventory: every production of spec/wat.peg (which
//   transcribes §6 directly) maps to a layout nonterminal or to a declared
//   atom/list/roots policy of the emitter, and every mapping row points back
//   at a real production. Both directions red. A struct dumper has no
//   production names and cannot pass.
//
//   MnemonicCountMatchesToml — 497 instruction constructors and terminals,
//   counted from the GENERATED artifacts (the TERM block, the tag enum),
//   never from the generator's own census. Adding an instruction moves these
//   and the gate goes red by design.
//
//   TheNodeIsTheSchema — the node header reaches C through asdl → json →
//   the inja template; the TERM block reaches it through gen_wat_ir's own
//   printf. Two paths from one source: this compares the ends name-for-name
//   at every id, plus the class partition and the arities the design fixes
//   (module constructors are leaves, instructions carry the operand spine,
//   the spine cons carries two).
//
// The peg heads are scanned line-wise (identifier at column 0 after the
// PRODUCTIONS keyword). pegc owns the grammar's real parse; this scan is
// only the inventory of production NAMES, and a head it misreads shows up
// as a red row here, not a silent pass.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#include "jav_reader.h"
#include "wat_check.h"
#include "wat_emit.h"
#include "wat_tnode.h"
#include "wat_render.h"

static int fails = 0;
static void CK(const char *msg, long got, long want) {
    int ok = (got == want);
    printf("  %-58s %6ld  [%s]\n", msg, got, ok ? "PASS" : "FAIL");
    fails += !ok;
}

static char* read_all(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) { printf("  cannot open %s\n", path); fails++; return NULL; }
    fseek(f, 0, SEEK_END);
    long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* s = malloc((size_t)n + 1);
    if (fread(s, 1, (size_t)n, f) != (size_t)n) { fclose(f); free(s); fails++; return NULL; }
    fclose(f);
    s[n] = 0;
    return s;
}

/* ── spec/wat.peg production heads ────────────────────────────────────── */
static char  peg_heads[128][64];
static int   n_peg_heads = 0;

static void scan_peg_heads(void) {
    char* text = read_all("../spec/wat.peg");
    if (!text) return;
    int in_prods = 0;
    for (char* line = strtok(text, "\n"); line; line = strtok(NULL, "\n")) {
        if (!in_prods) {
            if (!strncmp(line, "PRODUCTIONS", 11)) in_prods = 1;
            continue;
        }
        if (!isalpha((unsigned char)line[0])) continue;
        char head[64];
        int k = 0;
        while (k < 63 && (isalnum((unsigned char)line[k]) || line[k] == '_')) {
            head[k] = line[k];
            k++;
        }
        head[k] = 0;
        if (!strcmp(head, "END")) continue;     /* the pegc terminator */
        if (n_peg_heads < 128) {
            strcpy(peg_heads[n_peg_heads], head);
            n_peg_heads++;
        }
    }
    free(text);
}

static int peg_has(const char* prod) {
    for (int i = 0; i < n_peg_heads; i++)
        if (!strcmp(peg_heads[i], prod)) return 1;
    return 0;
}
static int maps_has_prod(const char* prod) {
    for (int i = 0; i < WAT_N_MAPS; i++)
        if (!strcmp(wat_maps[i].prod, prod)) return 1;
    return 0;
}
static int nts_has(const char* nt) {
    for (int i = 0; i < WAT_N_NTS; i++)
        if (!strcmp(wat_nts[i], nt)) return 1;
    return 0;
}

/* ── the TERM block of the generated grammar ──────────────────────────── */
static char* g_burg;

static void every_production_has_a_rule(void) {
    printf("  | EveryProductionHasARule (both directions vs spec/wat.peg)\n");
    int unmapped = 0, phantom = 0, bad_nt = 0, orphan_nt = 0;
    for (int i = 0; i < n_peg_heads; i++)
        if (!maps_has_prod(peg_heads[i])) {
            printf("  |   production %s has no mapping\n", peg_heads[i]);
            unmapped++;
        }
    for (int i = 0; i < WAT_N_MAPS; i++) {
        if (!peg_has(wat_maps[i].prod)) {
            printf("  |   mapping names phantom production %s\n", wat_maps[i].prod);
            phantom++;
        }
        if (!strcmp(wat_maps[i].kind, "nt") && !nts_has(wat_maps[i].target)) {
            printf("  |   mapping targets unknown nonterminal %s\n", wat_maps[i].target);
            bad_nt++;
        }
    }
    for (int i = 0; i < WAT_N_NTS; i++) {
        if (!strcmp(wat_nts[i], "grp")) continue;   /* the start symbol */
        int used = 0;
        for (int m = 0; m < WAT_N_MAPS; m++)
            if (!strcmp(wat_maps[m].kind, "nt") && !strcmp(wat_maps[m].target, wat_nts[i]))
                used = 1;
        if (!used) {
            printf("  |   nonterminal %s renders no production\n", wat_nts[i]);
            orphan_nt++;
        }
    }
    CK("peg heads found (a scan miss reads as 0)", n_peg_heads > 40, 1);
    CK("productions with no mapping", unmapped, 0);
    CK("mappings naming phantom productions", phantom, 0);
    CK("nt mappings to unknown nonterminals", bad_nt, 0);
    CK("nonterminals rendering no production", orphan_nt, 0);
}

static void mnemonic_count_matches_toml(void) {
    printf("  | MnemonicCountMatchesToml (counted from the artifacts)\n");
    int term_instr = 0, term_total = 0;
    for (char* p = g_burg; (p = strstr(p, "TERM ")) != NULL; p += 5) {
        if (p != g_burg && p[-1] != '\n') continue;
        term_total++;
        if (!strncmp(p + 5, "I_", 2)) term_instr++;
    }
    CK("instruction TERMs in the grammar", term_instr, 497);
    CK("WAT_N_INSTR", WAT_N_INSTR, 497);
    CK("tag count = module + instructions + spine",
       WAT_TT_TAG_COUNT, WAT_N_MODULE_CTOR + WAT_N_INSTR + 2);
    CK("TERM block covers every tag", term_total, WAT_TT_TAG_COUNT);
}

static void the_node_is_the_schema(void) {
    printf("  | TheNodeIsTheSchema (TERM block vs the generated node header)\n");
    int name_divergences = 0, ids_seen = 0;
    for (char* p = g_burg; (p = strstr(p, "TERM ")) != NULL; p += 5) {
        if (p != g_burg && p[-1] != '\n') continue;
        char name[80];
        int id = -1;
        if (sscanf(p, "TERM %79s = %d", name, &id) != 2) continue;
        ids_seen++;
        if (id < 0 || id >= WAT_TT_TAG_COUNT || strcmp(wat_tt_tag_name[id], name) != 0) {
            if (name_divergences < 5)
                printf("  |   id %d: grammar says %s, node header says %s\n",
                       id, name, (id >= 0 && id < WAT_TT_TAG_COUNT) ? wat_tt_tag_name[id] : "?");
            name_divergences++;
        }
    }
    CK("terminals compared", ids_seen, WAT_TT_TAG_COUNT);
    CK("name divergences at any id", name_divergences, 0);

    int bad_cls = 0, bad_arity = 0;
    for (int t = 0; t < WAT_TT_TAG_COUNT; t++) {
        if (t < WAT_N_MODULE_CTOR) {
            if (wat_tt_tag_cls[t] >= WAT_CLS_INSTR) bad_cls++;
            if (wat_tt_tag_arity[t] != 0) bad_arity++;     /* module ctors are leaves */
        } else if (t < WAT_TAG_OP_CONS) {
            if (wat_tt_tag_cls[t] != WAT_CLS_INSTR) bad_cls++;
            if (wat_tt_tag_arity[t] != 1) bad_arity++;     /* the operand spine */
        } else {
            if (wat_tt_tag_cls[t] != WAT_CLS_OPERANDS) bad_cls++;
            if (wat_tt_tag_arity[t] != (t == WAT_TAG_OP_CONS ? 2 : 0)) bad_arity++;
        }
    }
    CK("class partition breaks", bad_cls, 0);
    CK("arity breaks", bad_arity, 0);

    /* Every rule renders a real tag; every tag has a rule; every cost is the
     * byte length of the row's own literals — the formula the emitter's
     * width memo assumes. */
    int bad_tag = 0, bare_tags = 0, bad_cost = 0;
    static int covered[WAT_TT_TAG_COUNT];
    for (int r = 1; r < WAT_RULE_COUNT; r++) {
        const wat_render_row_t* row = &wat_render_rows[r];
        if (row->tag >= WAT_TT_TAG_COUNT) { bad_tag++; continue; }
        covered[row->tag] = 1;
        int want = row->head ? 2 + (int)strlen(row->head) : 0;
        for (const char* s = row->slots; *s; s++)
            if (*s == 'T') want += 6;
        if (row->cost != want) bad_cost++;
    }
    for (int t = 0; t < WAT_TT_TAG_COUNT; t++)
        if (!covered[t]) bare_tags++;
    CK("render rows naming bad tags", bad_tag, 0);
    CK("tags with no render row", bare_tags, 0);
    CK("row costs that are not their own literals", bad_cost, 0);
}

/* ── FlatWhenItFitsBrokenWhenItDoesnt ─────────────────────────────────────
 * §3.4's claim, pinned as two exact renderings of ONE body: wide enough, the
 * function is one line; one notch too narrow, it breaks at the OUTERMOST
 * node that does not fit — the function — and nowhere else: the type entry
 * stays flat, the typeuse line stays flat, and the fold stays flat. The
 * expected strings are written out verbatim; any drift in either direction
 * is a fail, not a style change. */
static void flat_when_it_fits_broken_when_it_doesnt(void) {
    printf("  | FlatWhenItFitsBrokenWhenItDoesnt\n");
    static const uint8_t wasm[] = {
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        0x01, 0x06, 0x01, 0x60, 0x01, 0x7f, 0x01, 0x7f,        /* (func (param i32) (result i32)) */
        0x03, 0x02, 0x01, 0x00,
        0x0a, 0x0c, 0x01, 0x0a, 0x00,
              0x20, 0x00, 0x41, 0x02, 0x6a, 0x41, 0x03, 0x6c, 0x0b,
    };
    static const char* const want_wide =
        "(module\n"
        "  (type (func (param i32) (result i32)))\n"
        "  (func (type 0) (param i32) (result i32) "
        "(i32.mul (i32.add (local.get 0) (i32.const 2)) (i32.const 3)))\n"
        ")\n";
    static const char* const want_narrow =
        "(module\n"
        "  (type (func (param i32) (result i32)))\n"
        "  (func\n"
        "    (type 0) (param i32) (result i32)\n"
        "    (i32.mul (i32.add (local.get 0) (i32.const 2)) (i32.const 3)))\n"
        ")\n";

    bbq_ctx_t c;
    bbq_ctx_init(&c, wasm, sizeof wasm);
    jav_module_t mod;
    memset(&mod, 0, sizeof mod);
    if (!jav_module_read(&c, &mod)) { printf("  |   read failed\n"); fails++; return; }
    bbq_ctx_free(&c);
    bbq_arena a;
    bbq_arena_init(&a, 65536);
    jav_err_t err = JAV_E_NONE;
    wat_check_ctx_t* wcx = wat_check_ctx_build(&mod, &a, &err);
    const char* txt = NULL;
    size_t len = 0;
    int ok = wcx && wat_emit_module(&mod, wcx, 120, &a, &txt, &len);
    CK("renders at width 120", ok, 1);
    if (ok) CK("one line, flat, verbatim", strcmp(txt, want_wide) == 0, 1);
    if (ok && strcmp(txt, want_wide) != 0) printf("  |   got:\n%s", txt);
    ok = wcx && wat_emit_module(&mod, wcx, 100, &a, &txt, &len);
    CK("renders at width 100", ok, 1);
    if (ok) CK("breaks at the func and nowhere else, verbatim",
               strcmp(txt, want_narrow) == 0, 1);
    if (ok && strcmp(txt, want_narrow) != 0) printf("  |   got:\n%s", txt);
    bbq_arena_free(&a);
    jav_module_free(&mod);
}

int main(void) {
    printf("── test_wat_layout ──────────────────────────────────────\n");
    scan_peg_heads();
    g_burg = read_all("../src/gen/wat_layout.burg");
    if (!g_burg) { printf("  FAIL: no grammar\n"); return 1; }
    every_production_has_a_rule();
    mnemonic_count_matches_toml();
    the_node_is_the_schema();
    flat_when_it_fits_broken_when_it_doesnt();
    if (fails) printf("  | FAIL: %d failed\n", fails);
    else       printf("  | all green\n");
    return fails ? 1 : 0;
}
